"use client";

import React, { useEffect, useState, useMemo } from "react";
import AddAssetModal from "@/components/main/AddAssetModal";
import AssetModal from "@/components/main/AssetModal";
import { useSession } from "next-auth/react";
import Link from "next/link";

interface NestedTask {
  id: string;
  taskNo?: string;
  taskType: string;
  startDate: string;
  endDate: string;
  taskNetProfit: number;
  status: string;
}

interface Asset {
  id: string;
  assetNo: string;
  assetName: string;
  category: string;
  purchaseDate: string;
  currentValue: number;
  availabilityStatus: "Available" | "On Set" | "Maintenance";
  tasks?: NestedTask[];
}

interface MetricCardProps {
  title: string;
  value: string;
  label: string;
  color?: string;
}

function MetricCard({ title, value, label, color = "text-foreground" }: MetricCardProps) {
  return (
    <div className="bg-card p-8 rounded-[2.5rem] border border-border group hover:shadow-xl hover:shadow-blue-500/5 transition-all">
      <p className="text-[9px] font-black text-muted-foreground uppercase mb-2 tracking-[0.2em]">{title}</p>
      <p className={`text-3xl font-black font-mono tracking-tighter ${color}`}>{value}</p>
      <p className="text-[9px] font-black text-muted-foreground uppercase mt-2 opacity-40">{label}</p>
    </div>
  );
}

interface UtilBarProps {
  label: string;
  percentage: number;
}

function UtilBar({ label, percentage }: UtilBarProps) {
  return (
    <div className="space-y-3">
      <div className="flex justify-between text-[9px] font-black uppercase tracking-widest">
        <span>{label}</span>
        <span className="text-blue-400">{percentage}%</span>
      </div>
      <div className="h-1 w-full bg-white/10 rounded-full overflow-hidden">
        <div 
          className="h-full bg-blue-500 transition-all duration-500" 
          style={{ width: `${percentage}%` }} 
        />
      </div>
    </div>
  );
}

export default function EquipmentPage() {
  const { data: session, status } = useSession();
  const agencyId = session?.user?.agencyId || "";

  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null);
  const [assets, setAssets] = useState<Asset[]>([]);
  const [metrics, setMetrics] = useState({ totalInvestment: 0, currentValue: 0, depreciation: 0 });
  const [activeCategory, setActiveCategory] = useState("ALL");
  const [loading, setLoading] = useState(true);
  const [expandedAssetIds, setExpandedAssetIds] = useState<Record<string, boolean>>({});

  const toggleRow = (id: string) => {
    setExpandedAssetIds(prev => ({ ...prev, [id]: !prev[id] }));
  };

  const refreshData = async () => {
    if (!agencyId) return;
    const res = await fetch(`/api/assets?agencyId=${agencyId}`);
    const data = await res.json();
    setAssets(data.assets || []);
    setMetrics(data.metrics || { totalInvestment: 0, currentValue: 0, depreciation: 0 });
  };

  useEffect(() => {
    if (status === "authenticated" && agencyId) {
      refreshData().finally(() => setLoading(false));
    } else if (status === "unauthenticated") {
      setLoading(false);
    }
  }, [status, agencyId]);

  

  const handleDelete = async (id: string) => {
    if (!confirm("Are you sure? This action is permanent.")) return;
    try {
      const res = await fetch(`/api/assets/${id}`, { method: "DELETE" });
      if (res.ok) refreshData();
    } catch (err) {
      console.error("Failed to delete asset");
    }
  };

  // Calculate the cumulative net profit generated by all registered equipment tasks
// Calculate the unique cumulative net profit generated by all registered equipment tasks
const totalEquipmentEarnings = useMemo(() => {
  const uniqueTasksMap = new Map<string, NestedTask>();

  // 1. Collect only unique tasks by ID across all assets
  assets.forEach((item) => {
    (item.tasks || []).forEach((task) => {
      if (task.id && !uniqueTasksMap.has(task.id)) {
        uniqueTasksMap.set(task.id, task);
      }
    });
  });

  // 2. Sum the net profit from the deduplicated task pool
  let grandTotal = 0;
  uniqueTasksMap.forEach((task) => {
    grandTotal += task.taskNetProfit || 0;
  });

  return grandTotal;
}, [assets]);

const filteredInventory = useMemo(() => {
  return activeCategory === "ALL" 
    ? assets 
    : assets.filter(item => item.category === activeCategory);
}, [activeCategory, assets]);


  if (status === "loading" || loading) {
    return <div className="p-8 font-black uppercase animate-pulse">Synchronizing Inventory...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto p-8 bg-background min-h-screen space-y-10">
      
      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end border-b border-border pb-8 gap-6">
        <div>
          <h1 className="text-3xl font-black text-foreground tracking-tight uppercase italic">Asset Inventory</h1>
          <p className="text-muted-foreground font-medium uppercase text-[10px] tracking-[0.3em] mt-1">Hardware & Capital Management</p>
        </div>
        
        <div className="flex bg-muted p-1 rounded-xl border border-border overflow-x-auto">
          {["ALL", "Camera", "Computing", "Lighting", "Audio"].map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-4 py-2 text-[9px] font-black uppercase tracking-widest rounded-lg transition-all whitespace-nowrap ${
                activeCategory === cat ? "bg-background text-blue-600 shadow-sm" : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* METRICS SECTION */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <MetricCard 
          title="Total Investment" 
          value={`$${metrics.totalInvestment.toLocaleString()}`} 
          label="Initial Capital" 
        />
        <MetricCard 
          title="Net Asset Value" 
          value={`$${metrics.currentValue.toLocaleString()}`} 
          label="Current Portfolio" 
          color="text-blue-600" 
        />
        <MetricCard 
          title="Equipment Earnings" 
          value={`+$${totalEquipmentEarnings.toLocaleString()}`} 
          label="Lifetime Yield from Tasks" 
          color="text-emerald-500" 
        />
      </div>

      {/* TABLE SECTION */}
      <div className="bg-card rounded-[2.5rem] border border-border shadow-sm overflow-hidden">
        <div className="p-6 border-b border-border bg-muted/20 flex justify-between items-center">
            <h3 className="font-black text-foreground text-[10px] uppercase tracking-[0.2em]">Master Asset Registry</h3>
            <button 
                onClick={() => setIsAddModalOpen(true)}
                className="bg-foreground text-background px-6 py-2 rounded-xl text-[9px] font-black uppercase tracking-widest hover:scale-[0.98] transition-all"
            >
                + Register New Asset
            </button>
        </div>

        <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
                <thead className="text-[9px] uppercase text-muted-foreground border-b border-border bg-muted/5">
                    <tr>
                        <th className="p-6 font-black">Asset Details</th>
                        <th className="p-6 font-black">Category</th>
                        <th className="p-6 font-black">Status</th>
                        <th className="p-6 text-right font-black">Valuation</th>
                        <th className="p-6 text-right font-black">Actions</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-border">
               {filteredInventory.map((item) => {
  const isExpanded = !!expandedAssetIds[item.id];
  
  // 1. Filter and sort upcoming tasks directly (No useMemo inside the loop!)
  const todayMidnight = new Date();
  todayMidnight.setHours(0, 0, 0, 0);
  
  const upcomingTasks = (item.tasks || [])
    .filter((task) => new Date(task.startDate) >= todayMidnight)
    .sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime());

  // 2. Sum profit exclusively from those upcoming filtered items
  const upcomingProfit = upcomingTasks.reduce((sum, t) => sum + (t.taskNetProfit || 0), 0);

  return (
    <React.Fragment key={item.id}>
      <tr className="hover:bg-muted/5 transition-colors group">
        <td className="p-6">
          <div className="flex items-start gap-3">
            <button 
              onClick={() => toggleRow(item.id)} 
              className="mt-1 text-muted-foreground hover:text-blue-600 transition-colors text-xs font-mono"
            >
              {isExpanded ? "▼" : "▶"}
            </button>
            <div>
              {/* WRAP NAME IN LINK COMPONENT */}
              <Link 
                href={`/dashboard/equipment/${item.id}`}
                className="block group/link"
              >
                <p className="font-black text-foreground text-sm uppercase group-hover:text-blue-600 group-hover/link:text-blue-500 group-hover/link:underline transition-all cursor-pointer">
                  {item.assetName}
                </p>
              </Link>
              <p className="text-[9px] text-muted-foreground font-mono uppercase mt-0.5">
                {item.assetNo || `ID-${item.id.slice(-4)}`} 
                {upcomingTasks.length > 0 && ` • (${upcomingTasks.length} Upcoming Tasks)`}
              </p>
            </div>
          </div>
        </td>
        <td className="p-6">
          <span className="text-[9px] font-black text-muted-foreground uppercase bg-muted px-2 py-1 rounded-md border border-border">
            {item.category}
          </span>
        </td>
        <td className="p-6">
          <div className="flex items-center gap-2">
            <span className={`w-2 h-2 rounded-full ${
              item.availabilityStatus === 'Available' ? 'bg-emerald-500' : 
              item.availabilityStatus === 'On Set' ? 'bg-blue-500' : 'bg-rose-500'
            }`} />
            <p className="text-[10px] font-black uppercase tracking-widest text-foreground">
              {item.availabilityStatus}
            </p>
          </div>
        </td>
        <td className="p-6 text-right">
          <p className="font-mono font-black text-sm text-foreground">${item.currentValue.toLocaleString()}</p>
          <p className="text-[9px] text-rose-500 font-black uppercase">Current Value</p>
        </td>
        <td className="p-6 text-right">
          <div className="flex justify-end gap-4 items-center">
            <button 
              onClick={() => toggleRow(item.id)}
              className="text-[9px] font-black uppercase tracking-widest text-muted-foreground hover:text-foreground underline"
            >
              {isExpanded ? "Hide Logs" : "View Schedule"}
            </button>
            <button 
              onClick={() => {
                setSelectedAsset(item);
                setIsEditModalOpen(true); 
              }}
              className="text-[9px] font-black uppercase tracking-widest text-blue-600 hover:underline"
            >
              Edit
            </button>
            <button 
              onClick={() => handleDelete(item.id)}
              className="text-[9px] font-black uppercase tracking-widest text-rose-500 hover:underline"
            >
              Delete
            </button>
          </div>
        </td>
      </tr>

      {/* EXPANDED SCHEDULE & PROFIT RUNTIME COMPONENT */}
      {isExpanded && (
        <tr className="bg-muted/10 border-l-2 border-blue-500">
          <td colSpan={5} className="p-6 bg-card/40">
            <div className="space-y-4">
              <div className="flex justify-between items-center border-b border-border/60 pb-2">
                <h4 className="text-[10px] font-black uppercase tracking-[0.15em] text-blue-500">
                  Upcoming Deployments & Asset Value Forecast
                </h4>
                <div className="text-right">
                  <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider mr-2">Pipeline Profit Projection:</span>
                  <span className="font-mono text-xs font-black text-emerald-500">${upcomingProfit.toLocaleString()}</span>
                </div>
              </div>

              {upcomingTasks.length === 0 ? (
                <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest py-2 italic">
                  No upcoming schedules or task requests registered for this equipment.
                </p>
              ) : (
                <div className="grid grid-cols-1 gap-2">
                  {upcomingTasks.map((task) => (
                    <div 
                      key={task.id} 
                      className="flex flex-col sm:flex-row justify-between items-start sm:items-center bg-background p-4 rounded-xl border border-border/80 gap-4 hover:border-blue-500/30 transition-all"
                    >
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-[10px] font-black text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                            {task.taskNo || `TSK-${task.id.slice(-4)}`}
                          </span>
                          <p className="text-xs font-black text-foreground uppercase tracking-wide">
                            {task.taskType}
                          </p>
                        </div>
                        <p className="text-[10px] text-muted-foreground uppercase font-medium mt-1">
                          Timeline: <span className="font-mono text-blue-500">{new Date(task.startDate).toLocaleDateString()}</span> → <span className="font-mono text-foreground">{new Date(task.endDate).toLocaleDateString()}</span>
                        </p>
                      </div>

                      <div className="flex items-center gap-6 self-end sm:self-center">
                        <div className="text-left sm:text-right">
                          <p className="text-[9px] font-black uppercase text-muted-foreground tracking-wider">Projected Yield</p>
                          <p className="font-mono text-xs font-black text-emerald-500">
                            +${task.taskNetProfit.toLocaleString()}
                          </p>
                        </div>
                        <span className={`text-[8px] font-black uppercase px-2 py-1 rounded tracking-widest ${
                          task.status === "COMPLETED" ? "bg-emerald-500/10 text-emerald-500" :
                          task.status === "FAILED" || task.status === "CANCELLED" ? "bg-rose-500/10 text-rose-500" :
                          "bg-blue-500/10 text-blue-500"
                        }`}>
                          {task.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </td>
        </tr>
      )}
    </React.Fragment>
  );
})}
                </tbody>
            </table>
        </div>
      </div>

      {/* MODALS SECTION */}
      <AddAssetModal 
          isOpen={isAddModalOpen} 
          onClose={() => setIsAddModalOpen(false)} 
          onRefresh={refreshData}
          agencyId={agencyId}
      />

      {selectedAsset && (
        <AssetModal 
          isOpen={isEditModalOpen} 
          onClose={() => {
            setIsEditModalOpen(false);
            setSelectedAsset(null);
          }} 
          onRefresh={refreshData}
          agencyId={agencyId}
          initialData={selectedAsset}
        />
      )}

      {/* UTILIZATION SECTION */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <div className="bg-slate-950 rounded-[2.5rem] p-10 text-white">
              <h4 className="font-black text-blue-400 uppercase text-[9px] tracking-[0.3em] mb-8">Hardware Utilization</h4>
              <div className="space-y-8">
                  <UtilBar label="Cinema Cameras" percentage={78} />
                  <UtilBar label="Edit Suites" percentage={92} />
                  <UtilBar label="Lighting Kits" percentage={45} />
              </div>
          </div>
          <div className="bg-blue-600 rounded-[2.5rem] p-10 text-white flex flex-col justify-between">
              <p className="font-black uppercase text-[10px] tracking-widest opacity-80">Maintenance Alert</p>
              <p className="text-2xl font-black leading-tight mt-4 italic">
                3 Assets require routine sensor cleaning this week.
              </p>
              <button className="mt-8 bg-white text-blue-600 w-full py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-opacity-90 transition-all">
                Schedule Service
              </button>
          </div>
      </div>
    </div>
  );
}