import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions"; // Adjust to matches your auth options path

export async function GET() {
  try {
    const session = await getServerSession(authOptions);
    const agencyId = session?.user?.agencyId;
    
    if (!agencyId) {
      return NextResponse.json({ error: "Unauthorized access context" }, { status: 401 });
    }

    const employees = await prisma.user.findMany({
      where: { agencyId },
      include: {
        // FIX 1: Match the exact schema relation name 'tasks'
        tasks: { 
          where: { agencyId } 
        },
        // FIX 2: Include your new ledger to aggregate true earnings/deductions
        financialLedger: {
          where: { status: "APPROVED" }
        }
      }
    });

    const formattedEmployees = employees.map((emp) => {
      const assignedTasks = emp.tasks || [];
      const ledger = emp.financialLedger || [];

      // Lifetime Revenue and Profit generated by this employee's tasks
      const totalTaskRevenue = assignedTasks.reduce(
        (sum, t) => sum + (Number(t.internalCost) || 0), 0
      );

      const netProfitGenerated = assignedTasks.reduce(
        (sum, t) => sum + (Number(t.taskNetProfit) || 0), 0
      );

      // Extract variations from your ledger updates
      const totalCommissionsEarned = ledger
        .filter(t => t.type === "COMMISSION" || t.type === "OVERTIME")
        .reduce((sum, t) => sum + t.amount, 0);

      const totalDeductionsIncurred = ledger
        .filter(t => t.type.startsWith("DEDUCTION"))
        .reduce((sum, t) => sum + Math.abs(t.amount), 0);

      // Financial Liability Calculation based on User Type
      // Freelancers cost their combined task commissions; Full-Timers cost base salary + commissions - penalties
      const basePay = Number(emp.baseSalary) || 0;
      const productionCost = emp.userType === "FREELANCER"
        ? totalCommissionsEarned
        : (basePay + totalCommissionsEarned - totalDeductionsIncurred);

      const efficiency = productionCost > 0 
        ? (totalTaskRevenue / productionCost).toFixed(2) 
        : "0.00";

      return {
        id: emp.id,
        name: emp.name,
        role: emp.role,
        userType: emp.userType,
        walletBalance: emp.walletBalance || 0,
        baseSalary: basePay,
        totalTaskRevenue,
        netProfitGenerated, 
        totalCommissionsEarned,
        totalDeductionsIncurred,
        efficiencyRate: efficiency,
        tasks: assignedTasks.map(t => ({
          id: t.id,
          taskNo: t.taskNo,
          revenue: Number(t.internalCost) || 0,
          taskNetProfit: Number(t.taskNetProfit) || 0,
          date: t.createdAt ? new Date(t.createdAt).toISOString().split('T')[0] : "" 
        }))
      };
    });

    // Global Agency Metrics Breakdown
    const totalAgencyRevenue = formattedEmployees.reduce((sum, e) => sum + e.totalTaskRevenue, 0);
    const totalAgencyNetProfit = formattedEmployees.reduce((sum, e) => sum + e.netProfitGenerated, 0);
    const totalCurrentWalletLiability = formattedEmployees.reduce((sum, e) => sum + e.walletBalance, 0);
    
    const totalAgencyLiability = formattedEmployees.reduce((sum, e) => {
      return sum + (e.userType === "FREELANCER" ? e.totalCommissionsEarned : (e.baseSalary + e.totalCommissionsEarned - e.totalDeductionsIncurred));
    }, 0);

    const globalEfficiency = totalAgencyLiability > 0 ? (totalAgencyRevenue / totalAgencyLiability).toFixed(2) : "0.00";
    const avgRevenuePerHead = formattedEmployees.length > 0 ? (totalAgencyRevenue / formattedEmployees.length) : 0;

    return NextResponse.json({
      employees: formattedEmployees,
      metrics: {
        totalRevenue: totalAgencyRevenue,
        totalNetProfit: totalAgencyNetProfit,
        totalUnpaidWalletLiability: totalCurrentWalletLiability, // Capital currently outstanding to pay your staff
        globalEfficiency,
        avgRevenuePerHead,
        employeeCount: formattedEmployees.length
      }
    });

  } catch (error) {
    console.error("GET_PERSONNEL_FINANCE_ERROR:", error);
    return NextResponse.json({ error: "Internal Database Metric Pipeline Failure" }, { status: 500 });
  }
}